config:
  backup: true
  banner: false
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
  showdiff: true
  workdir: ~/git/dotfiles/dotdrop
dotfiles:
  f_bash_profile:
    dst: ~/.bash_profile
    src: bash_profile
  f_bashrc:
    dst: ~/.bashrc
    src: bashrc
  f_cheat:
    dst: ~/.local/bin/cheat
    src: local/bin/cheat
  f_curlrc:
    dst: ~/.curlrc
    src: curlrc
  f_force-hibernate:
    dst: ~/.local/bin/force-hibernate
    src: local/bin/force-hibernate
  f_gitconfig:
    dst: ~/.gitconfig
    src: gitconfig
  f_ifconfigc:
    dst: ~/.local/bin/ifconfigc
    src: local/bin/ifconfigc
  f_inttoip:
    dst: ~/.local/bin/inttoip
    src: local/bin/inttoip
  f_iptoint:
    dst: ~/.local/bin/iptoint
    src: local/bin/iptoint
  f_keybindings.json:
    dst: ~/.config/Code/User/keybindings.json
    src: config/Code/User/keybindings.json
  f_myip:
    dst: ~/.local/bin/myip
    src: local/bin/myip
  f_profile:
    dst: ~/.profile
    src: profile
  f_rr:
    dst: ~/.local/bin/rr
    src: local/bin/rr
  f_settings.json:
    dst: ~/.config/Code/User/settings.json
    src: config/Code/User/settings.json
  f_tinyurl:
    dst: ~/.local/bin/tinyurl
    src: local/bin/tinyurl
  f_tmux.conf:
    dst: ~/.tmux.conf
    src: tmux.conf
  f_vimrc:
    dst: ~/.vimrc
    src: vimrc
  f_weather:
    dst: ~/.local/bin/weather
    src: local/bin/weather
  f_install_dotnet_sdk:
    dst: ~/.local/bin/install_dotnet_sdk
    src: local/bin/install_dotnet_sdk
  f_whereami:
    dst: ~/.local/bin/whereami
    src: local/bin/whereami
  f_zshrc:
    dst: ~/.zshrc
    src: zshrc
  f_killport:
    dst: ~/.local/bin/killport
    src: local/bin/killport
  f_gitignore:
    src: gitignore
    dst: ~/.gitignore
  f_i3_config:
    src: config/i3/config
    dst: ~/.config/i3/config
  f_70-synaptics.conf:
    src: usr/share/X11/xorg.conf.d/70-synaptics.conf
    dst: /usr/share/X11/xorg.conf.d/70-synaptics.conf
  f_vconsole.conf:
    src: etc/vconsole.conf
    dst: /etc/vconsole.conf
  f_docker_config.json:
    src: docker/config.json
    dst: ~/.docker/config.json
  f_rofi_config.rasi:
    src: config/rofi/config.rasi
    dst: ~/.config/rofi/config.rasi
  f_i3status.conf:
    src: etc/i3status.conf
    dst: /etc/i3status.conf
  f_wtfutil_config.yml:
    src: config/wtf/config.yml
    dst: ~/.config/wtf/config.yml
  f_xresources:
    src: Xresources
    dst: ~/.Xresources
  f_clr_dev:
    src: init/clr.sh
    dst: ~/init/clr.sh
profiles:
  tdesktop:
    dotfiles:
      - f_force-hibernate
      - f_myip
      - f_weather
      - f_whereami
      - f_iptoint
      - f_inttoip
      - f_vimrc
      - f_profile
      - f_bashrc
      - f_zshrc
      - f_keybindings.json
      - f_settings.json
      - f_tmux.conf
      - f_gitconfig
      - f_curlrc
      - f_bash_profile
      - f_ifconfigc
      - f_tinyurl
      - f_cheat
      - f_rr
      - f_killport
      - f_gitignore
      - f_docker_config.json
      - f_install_dotnet_sdk
      - f_clr_dev
      - f_i3_config
      - f_i3status.conf
      - f_xresources
  surface:
    dotfiles:
      - f_i3_config
      - f_70-synaptics.conf
      - f_vconsole.conf
      - f_rofi_config.rasi
      - f_i3status.conf
      - f_xresources
      - f_tmux.conf
      - f_docker_config.json
