config:
  backup: true
  banner: false
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
  showdiff: true
  workdir: ~/git/dotfiles/dotdrop
dotfiles:
  f_bashrc:
    dst: ~/.bashrc
    src: bashrc
  f_cheat:
    dst: ~/.local/bin/cheat
    src: local/bin/cheat
  f_gitconfig:
    dst: ~/.gitconfig
    src: gitconfig
  f_ifconfigc:
    dst: ~/.local/bin/ifconfigc
    src: local/bin/ifconfigc
  f_inttoip:
    dst: ~/.local/bin/inttoip
    src: local/bin/inttoip
  f_iptoint:
    dst: ~/.local/bin/iptoint
    src: local/bin/iptoint
  f_keybindings.json:
    dst: ~/.config/Code/User/keybindings.json
    src: config/Code/User/keybindings.json
  f_myip:
    dst: ~/.local/bin/myip
    src: local/bin/myip
  f_profile:
    dst: ~/.profile
    src: profile
  f_rr:
    dst: ~/.local/bin/rr
    src: local/bin/rr
  f_settings.json:
    dst: ~/.config/Code/User/settings.json
    src: config/Code/User/settings.json
  f_tinyurl:
    dst: ~/.local/bin/tinyurl
    src: local/bin/tinyurl
  f_tmux.conf:
    dst: ~/.tmux.conf
    src: tmux.conf
  f_vimrc:
    dst: ~/.vimrc
    src: vimrc
  f_weather:
    dst: ~/.local/bin/weather
    src: local/bin/weather
  f_whereami:
    dst: ~/.local/bin/whereami
    src: local/bin/whereami
  f_zshrc:
    dst: ~/.zshrc
    src: zshrc
  f_killport:
    dst: ~/.local/bin/killport
    src: local/bin/killport
  f_gitignore:
    src: gitignore
    dst: ~/.gitignore
  f_i3_config:
    src: config/i3/config
    dst: ~/.config/i3/config
  f_vconsole.conf:
    src: etc/vconsole.conf
    dst: /etc/vconsole.conf
  f_docker_config.json:
    src: docker/config.json
    dst: ~/.docker/config.json
  f_rofi_config.rasi:
    src: config/rofi/config.rasi
    dst: ~/.config/rofi/config.rasi
  f_i3status.conf:
    src: etc/i3status.conf
    dst: /etc/i3status.conf
  f_xresources:
    src: Xresources
    dst: ~/.Xresources
  f_settings_settings.json:
    src: config/1Password/settings/settings.json
    dst: ~/.config/1Password/settings/settings.json
  f_htoprc:
    src: config/htop/htoprc
    dst: ~/.config/htop/htoprc
profiles:
  raptor:
    dotfiles:
    - f_settings_settings.json
    - f_htoprc
