config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
dotfiles:
  f_bash_profile:
    dst: ~/.bash_profile
    src: bash_profile
  f_bashrc:
    dst: ~/.bashrc
    src: bashrc
  f_cheat:
    dst: ~/.local/bin/cheat
    src: local/bin/cheat
  f_curlrc:
    dst: ~/.curlrc
    src: curlrc
  f_force-hibernate:
    dst: ~/.local/bin/force-hibernate
    src: local/bin/force-hibernate
  f_gitconfig:
    dst: ~/.gitconfig
    src: gitconfig
  f_ifconfigc:
    dst: ~/.local/bin/ifconfigc
    src: local/bin/ifconfigc
  f_inttoip:
    dst: ~/.local/bin/inttoip
    src: local/bin/inttoip
  f_iptoint:
    dst: ~/.local/bin/iptoint
    src: local/bin/iptoint
  f_keybindings.json:
    dst: ~/.config/Code/User/keybindings.json
    src: config/Code/User/keybindings.json
  f_myip:
    dst: ~/.local/bin/myip
    src: local/bin/myip
  f_profile:
    dst: ~/.profile
    src: profile
  f_rr:
    dst: ~/.local/bin/rr
    src: local/bin/rr
  f_settings.json:
    dst: ~/.config/Code/User/settings.json
    src: config/Code/User/settings.json
  f_tinyurl:
    dst: ~/.local/bin/tinyurl
    src: local/bin/tinyurl
  f_tmux.conf:
    dst: ~/.tmux.conf
    src: tmux.conf
  f_vimrc:
    dst: ~/.vimrc
    src: vimrc
  f_weather:
    dst: ~/.local/bin/weather
    src: local/bin/weather
  f_whereami:
    dst: ~/.local/bin/whereami
    src: local/bin/whereami
  f_zshrc:
    dst: ~/.zshrc
    src: zshrc
  f_kill_on_port:
    dst: ~/.local/bin/kill_on_port
    src: local/bin/kill_on_port
  f_gitignore:
    src: gitignore
    dst: ~/.gitignore
  f_config:
    src: config/i3/config
    dst: ~/.config/i3/config
  f_70-synaptics.conf:
    src: usr/share/X11/xorg.conf.d/70-synaptics.conf
    dst: /usr/share/X11/xorg.conf.d/70-synaptics.conf
profiles:
  tdesktop:
    dotfiles:
    - f_force-hibernate
    - f_myip
    - f_weather
    - f_whereami
    - f_iptoint
    - f_inttoip
    - f_vimrc
    - f_profile
    - f_bashrc
    - f_zshrc
    - f_keybindings.json
    - f_settings.json
    - f_tmux.conf
    - f_gitconfig
    - f_curlrc
    - f_bash_profile
    - f_ifconfigc
    - f_tinyurl
    - f_cheat
    - f_rr
    - f_kill_on_port
    - f_gitignore
  surface:
    dotfiles:
    - f_config
    - f_70-synaptics.conf
